export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE_FIELD';
export const CLEAR_FIELDS = 'CLEAR_FIELDS';
export const SET_SERVICE = 'SET_SERVICE';

