export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_READY = 'FETCH_READY'

export const REMOVE_SERVICE = 'REMOVE_SERVICE'

export const SERVICE_ADD_REQUEST = 'SERVICE_ADD_REQUEST'
export const SERVICE_ADD_ERROR = 'SERVICE_ADD_ERROR'
export const SERVICE_ADD_SUCCESS = 'SERVICE_ADD_SUCCESS'
export const SERVICE_CHANGE_FIELD = 'SERVICE_CHANGE_FIELD';
export const FETCH_SERVICE_READY = 'FETCH_SERVICE_READY'